import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import ThemeRegistry from "../../theme/ThemeRegistery";
import Header from "./components/Header";
import { Box } from "@mui/material";
import AdvBox from "./components/AdvBox";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeRegistry options={{ key: 'mui-theme' }}>
            <Box>
              <Header />
              <Box>
                {children}
              </Box>
            </Box>
          </ThemeRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
